using Microsoft.CodeAnalysis;
using MSBuild.SDK.SystemWeb.WebForms.Tests.Infrastructure;

namespace MSBuild.SDK.SystemWeb.WebForms.Tests;

public class DesignerGeneratorTests
{
    private const string PageDirective = "<%@ Page Language=\"C#\" AutoEventWireup=\"true\" CodeBehind=\"Default.aspx.cs\" Inherits=\"WebApp._Default\" %>\r\n";
    private const string DefaultCodeBehind = "namespace WebApp { public partial class _Default : System.Web.UI.Page { } }";
    private const string DefaultHint = "Default.aspx.designer.g.cs";

    private const string WebControls = "global::System.Web.UI.WebControls.";
    private const string HtmlControls = "global::System.Web.UI.HtmlControls.";

    private static GeneratorTestHost Page(string body, string codeBehind = DefaultCodeBehind)
        => new GeneratorTestHost().WithMarkup("Default.aspx", PageDirective + body).WithSource("Default.aspx.cs", codeBehind);

    [NetFx48Fact]
    public void Basic_page_generates_fields_in_markup_order_with_vs_layout()
    {
        var result = Page(
            "<html><body><form id=\"form1\" runat=\"server\">" +
            "<asp:Label ID=\"lblName\" runat=\"server\" /><asp:TextBox ID=\"txtName\" runat=\"server\"></asp:TextBox>" +
            "</form></body></html>").Run();

        DesignerAssert.NoDiagnostics(result);
        var source = result.GetSource(DefaultHint);
        Assert.Contains("// <auto-generated>", source);
        Assert.Contains("namespace WebApp {", source);
        Assert.Contains("partial class _Default {", source);
        DesignerAssert.HasField(source, HtmlControls + "HtmlForm", "form1");
        DesignerAssert.HasField(source, WebControls + "Label", "lblName");
        DesignerAssert.HasField(source, WebControls + "TextBox", "txtName");
        Assert.True(source.IndexOf("form1;", StringComparison.Ordinal) < source.IndexOf("lblName;", StringComparison.Ordinal));
        Assert.True(source.IndexOf("lblName;", StringComparison.Ordinal) < source.IndexOf("txtName;", StringComparison.Ordinal));
        Assert.Contains("/// To modify move field declaration from designer file to code-behind file.", source);
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Html_server_controls_map_to_HtmlControls_types()
    {
        var result = Page(
            "<html><head id=\"head1\" runat=\"server\"><title>t</title></head><body>" +
            "<form id=\"form1\" runat=\"server\">" +
            "<input id=\"txt\" runat=\"server\" /><input type=\"password\" id=\"pwd\" runat=\"server\" />" +
            "<input type=\"checkbox\" id=\"chk\" runat=\"server\" /><input type=\"hidden\" id=\"hid\" runat=\"server\" />" +
            "<input type=\"file\" id=\"fil\" runat=\"server\" /><input type=\"submit\" id=\"sub\" runat=\"server\" />" +
            "<input type=\"range\" id=\"rng\" runat=\"server\" />" +
            "<select id=\"sel\" runat=\"server\"><option>1</option></select><textarea id=\"txa\" runat=\"server\"></textarea>" +
            "<table id=\"tbl\" runat=\"server\"><tr id=\"row\" runat=\"server\"><td id=\"cell\" runat=\"server\"></td></tr></table>" +
            "<div id=\"div\" runat=\"server\"></div><a id=\"lnk\" runat=\"server\" href=\"#\">x</a>" +
            "<span id=\"notServer\"></span>" +
            "</form></body></html>").Run();

        var source = result.GetSource(DefaultHint);
        DesignerAssert.HasField(source, HtmlControls + "HtmlHead", "head1");
        DesignerAssert.HasField(source, HtmlControls + "HtmlForm", "form1");
        DesignerAssert.HasField(source, HtmlControls + "HtmlInputText", "txt");
        DesignerAssert.HasField(source, HtmlControls + "HtmlInputPassword", "pwd");
        DesignerAssert.HasField(source, HtmlControls + "HtmlInputCheckBox", "chk");
        DesignerAssert.HasField(source, HtmlControls + "HtmlInputHidden", "hid");
        DesignerAssert.HasField(source, HtmlControls + "HtmlInputFile", "fil");
        DesignerAssert.HasField(source, HtmlControls + "HtmlInputSubmit", "sub");
        DesignerAssert.HasField(source, HtmlControls + "HtmlInputGenericControl", "rng");
        DesignerAssert.HasField(source, HtmlControls + "HtmlSelect", "sel");
        DesignerAssert.HasField(source, HtmlControls + "HtmlTextArea", "txa");
        DesignerAssert.HasField(source, HtmlControls + "HtmlTable", "tbl");
        DesignerAssert.HasField(source, HtmlControls + "HtmlTableRow", "row");
        DesignerAssert.HasField(source, HtmlControls + "HtmlTableCell", "cell");
        DesignerAssert.HasField(source, HtmlControls + "HtmlGenericControl", "div");
        DesignerAssert.HasField(source, HtmlControls + "HtmlAnchor", "lnk");
        DesignerAssert.HasNoField(source, "notServer");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Controls_inside_multi_instance_templates_get_no_fields()
    {
        var result = Page(
            "<form id=\"form1\" runat=\"server\">" +
            "<asp:Repeater ID=\"rpt\" runat=\"server\"><HeaderTemplate><asp:Label ID=\"lblHeader\" runat=\"server\" /></HeaderTemplate>" +
            "<ItemTemplate><asp:Label ID=\"lblItem\" runat=\"server\" Text='<%# Container.DataItem %>' /></ItemTemplate></asp:Repeater>" +
            "<asp:GridView ID=\"gv\" runat=\"server\"><Columns><asp:BoundField DataField=\"a\" />" +
            "<asp:TemplateField><ItemTemplate><asp:Label ID=\"lblCell\" runat=\"server\" /></ItemTemplate></asp:TemplateField>" +
            "</Columns></asp:GridView>" +
            "<asp:Label ID=\"lblAfter\" runat=\"server\" />" +
            "</form>").Run();

        DesignerAssert.NoDiagnostics(result);
        var source = result.GetSource(DefaultHint);
        DesignerAssert.HasField(source, WebControls + "Repeater", "rpt");
        DesignerAssert.HasField(source, WebControls + "GridView", "gv");
        DesignerAssert.HasField(source, WebControls + "Label", "lblAfter");
        DesignerAssert.HasNoField(source, "lblHeader");
        DesignerAssert.HasNoField(source, "lblItem");
        DesignerAssert.HasNoField(source, "lblCell");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Controls_inside_single_instance_templates_and_collection_properties_get_fields()
    {
        var result = Page(
            "<form id=\"form1\" runat=\"server\"><asp:ScriptManager ID=\"sm\" runat=\"server\" />" +
            "<asp:UpdatePanel ID=\"up\" runat=\"server\"><ContentTemplate><asp:Label ID=\"lblTime\" runat=\"server\" /></ContentTemplate>" +
            "<Triggers><asp:AsyncPostBackTrigger ControlID=\"btn\" /></Triggers></asp:UpdatePanel>" +
            "<asp:Wizard ID=\"wz\" runat=\"server\"><WizardSteps><asp:WizardStep ID=\"step1\" runat=\"server\"><asp:Label ID=\"lblStep\" runat=\"server\" /></asp:WizardStep></WizardSteps></asp:Wizard>" +
            "<asp:Button ID=\"btn\" runat=\"server\" />" +
            "</form>").Run();

        DesignerAssert.NoDiagnostics(result);
        var source = result.GetSource(DefaultHint);
        DesignerAssert.HasField(source, "global::System.Web.UI.ScriptManager", "sm");
        DesignerAssert.HasField(source, "global::System.Web.UI.UpdatePanel", "up");
        DesignerAssert.HasField(source, WebControls + "Label", "lblTime");
        DesignerAssert.HasField(source, WebControls + "Wizard", "wz");
        DesignerAssert.HasField(source, WebControls + "WizardStep", "step1");
        DesignerAssert.HasField(source, WebControls + "Label", "lblStep");
        DesignerAssert.HasField(source, WebControls + "Button", "btn");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void User_controls_registered_by_directive_are_typed_and_get_their_own_designer()
    {
        var result = new GeneratorTestHost()
            .WithMarkup("Default.aspx",
                PageDirective +
                "<%@ Register TagPrefix=\"uc\" TagName=\"Hello\" Src=\"~/Controls/Hello.ascx\" %>" +
                "<%@ Register TagPrefix=\"uc2\" TagName=\"Hello\" Src=\"Controls/Hello.ascx\" %>" +
                "<form id=\"form1\" runat=\"server\"><uc:Hello ID=\"hello1\" runat=\"server\" /><uc2:hello ID=\"hello2\" runat=\"server\" /></form>")
            .WithMarkup("Controls/Hello.ascx",
                "<%@ Control Language=\"C#\" CodeBehind=\"Hello.ascx.cs\" Inherits=\"WebApp.Controls.Hello\" %><asp:Label ID=\"lblHello\" runat=\"server\" />")
            .WithSource("Default.aspx.cs", DefaultCodeBehind)
            .WithSource("Controls/Hello.ascx.cs", "namespace WebApp.Controls { public partial class Hello : System.Web.UI.UserControl { } }")
            .Run();

        DesignerAssert.NoDiagnostics(result);
        var page = result.GetSource(DefaultHint);
        DesignerAssert.HasField(page, "global::WebApp.Controls.Hello", "hello1");
        DesignerAssert.HasField(page, "global::WebApp.Controls.Hello", "hello2");
        var control = result.GetSource("Controls_Hello.ascx.designer.g.cs");
        Assert.Contains("namespace WebApp.Controls {", control);
        Assert.Contains("partial class Hello {", control);
        DesignerAssert.HasField(control, WebControls + "Label", "lblHello");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Web_config_registrations_resolve_source_namespaces_and_user_controls()
    {
        var result = new GeneratorTestHost()
            .WithWebConfig(
                "<configuration><system.web><pages><controls>" +
                "<add tagPrefix=\"ex\" namespace=\"WebApp.Controls\" />" +
                "<add tagPrefix=\"uc\" tagName=\"Hello\" src=\"~/Controls/Hello.ascx\" />" +
                "</controls></pages></system.web></configuration>")
            .WithMarkup("Default.aspx", PageDirective + "<form id=\"form1\" runat=\"server\"><ex:GreetingLabel ID=\"greet\" runat=\"server\" /><uc:Hello ID=\"hello\" runat=\"server\" /></form>")
            .WithMarkup("Controls/Hello.ascx", "<%@ Control Inherits=\"WebApp.Controls.Hello\" %>")
            .WithSource("Default.aspx.cs", DefaultCodeBehind)
            .WithSource("Controls/Controls.cs",
                "namespace WebApp.Controls { public class GreetingLabel : System.Web.UI.WebControls.Label { } public partial class Hello : System.Web.UI.UserControl { } }")
            .Run();

        DesignerAssert.NoDiagnostics(result);
        var source = result.GetSource(DefaultHint);
        DesignerAssert.HasField(source, "global::WebApp.Controls.GreetingLabel", "greet");
        DesignerAssert.HasField(source, "global::WebApp.Controls.Hello", "hello");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void MasterType_and_PreviousPageType_produce_typed_properties()
    {
        var result = new GeneratorTestHost()
            .WithMarkup("Site.Master",
                "<%@ Master Language=\"C#\" CodeBehind=\"Site.Master.cs\" Inherits=\"WebApp.SiteMaster\" %>" +
                "<html><body><form id=\"form1\" runat=\"server\"><asp:ContentPlaceHolder ID=\"MainContent\" runat=\"server\" /></form></body></html>")
            .WithMarkup("Default.aspx",
                "<%@ Page Language=\"C#\" MasterPageFile=\"~/Site.Master\" CodeBehind=\"Default.aspx.cs\" Inherits=\"WebApp._Default\" %>" +
                "<%@ MasterType VirtualPath=\"~/Site.Master\" %>" +
                "<%@ PreviousPageType TypeName=\"WebApp.Search\" %>" +
                "<asp:Content ID=\"Content1\" ContentPlaceHolderID=\"MainContent\" runat=\"server\"><asp:Label ID=\"lblInContent\" runat=\"server\" /></asp:Content>")
            .WithSource("Code.cs",
                "namespace WebApp { public partial class SiteMaster : System.Web.UI.MasterPage { } public partial class _Default : System.Web.UI.Page { } public class Search : System.Web.UI.Page { } }")
            .Run();

        DesignerAssert.NoDiagnostics(result);
        var page = result.GetSource(DefaultHint);
        Assert.Contains("public new global::WebApp.SiteMaster Master {", page);
        Assert.Contains("return ((global::WebApp.SiteMaster)(base.Master));", page);
        Assert.Contains("public new global::WebApp.Search PreviousPage {", page);
        DesignerAssert.HasNoField(page, "Content1");
        DesignerAssert.HasField(page, WebControls + "Label", "lblInContent");

        var master = result.GetSource("Site.Master.designer.g.cs");
        DesignerAssert.HasField(master, WebControls + "ContentPlaceHolder", "MainContent");
        DesignerAssert.HasField(master, HtmlControls + "HtmlForm", "form1");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Members_already_declared_in_code_behind_or_base_classes_are_skipped()
    {
        var result = Page(
            "<form id=\"form1\" runat=\"server\"><asp:Label ID=\"lblName\" runat=\"server\" /><asp:TextBox ID=\"txtBase\" runat=\"server\" />" +
            "<asp:Label ID=\"lblPrivateInBase\" runat=\"server\" /><asp:Label ID=\"lblGenerated\" runat=\"server\" /></form>",
            "namespace WebApp { " +
            "public class BasePage : System.Web.UI.Page { protected System.Web.UI.WebControls.TextBox txtBase; private System.Web.UI.WebControls.Label lblPrivateInBase; } " +
            "public partial class _Default : BasePage { protected System.Web.UI.WebControls.Label lblName; } }").Run();

        DesignerAssert.NoDiagnostics(result);
        var source = result.GetSource(DefaultHint);
        DesignerAssert.HasNoField(source, "lblName");
        DesignerAssert.HasNoField(source, "txtBase");
        DesignerAssert.HasField(source, WebControls + "Label", "lblPrivateInBase");
        DesignerAssert.HasField(source, WebControls + "Label", "lblGenerated");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Legacy_designer_files_coexist_with_the_generator()
    {
        var result = Page(
            "<form id=\"form1\" runat=\"server\"><asp:Label ID=\"lblName\" runat=\"server\" /><asp:Label ID=\"lblNew\" runat=\"server\" /></form>")
            .WithSource("Default.aspx.designer.cs",
                "namespace WebApp { public partial class _Default { protected global::System.Web.UI.HtmlControls.HtmlForm form1; protected global::System.Web.UI.WebControls.Label lblName; } }")
            .Run();

        DesignerAssert.NoDiagnostics(result);
        var source = result.GetSource(DefaultHint);
        DesignerAssert.HasNoField(source, "form1");
        DesignerAssert.HasNoField(source, "lblName");
        DesignerAssert.HasField(source, WebControls + "Label", "lblNew");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Tag_names_and_attributes_are_case_insensitive()
    {
        var result = Page("<FORM ID=\"form1\" RUNAT=\"Server\"><ASP:LABEL id=\"lbl\" Runat=\"server\" /></FORM>").Run();

        DesignerAssert.NoDiagnostics(result);
        var source = result.GetSource(DefaultHint);
        DesignerAssert.HasField(source, HtmlControls + "HtmlForm", "form1");
        DesignerAssert.HasField(source, WebControls + "Label", "lbl");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Unresolved_control_reports_SWWF001_and_other_fields_still_generate()
    {
        var result = Page("<form id=\"form1\" runat=\"server\"><foo:Bar ID=\"bar\" runat=\"server\" /><asp:Label ID=\"lbl\" runat=\"server\" /></form>").Run();

        var diagnostic = DesignerAssert.HasDiagnostic(result, "SWWF001");
        Assert.Equal(DiagnosticSeverity.Warning, diagnostic.Severity);
        Assert.Contains("foo:Bar", diagnostic.GetMessage());
        Assert.EndsWith("Default.aspx", diagnostic.Location.GetLineSpan().Path);
        var source = result.GetSource(DefaultHint);
        DesignerAssert.HasNoField(source, "bar");
        DesignerAssert.HasField(source, WebControls + "Label", "lbl");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Script_blocks_and_server_comments_are_ignored_but_html_comments_are_not()
    {
        var result = Page(
            "<script runat=\"server\">void Page_Load(object s, System.EventArgs e) { /* <asp:Label ID=\"ghost\" runat=\"server\" /> */ }</script>" +
            "<%-- <asp:Label ID=\"commented\" runat=\"server\" /> --%>" +
            "<!-- <asp:Label ID=\"inHtmlComment\" runat=\"server\" /> -->" +
            "<form id=\"form1\" runat=\"server\"><asp:Label ID=\"dup\" runat=\"server\" /><asp:Label ID=\"dup\" runat=\"server\" /></form>").Run();

        DesignerAssert.NoDiagnostics(result);
        var source = result.GetSource(DefaultHint);
        DesignerAssert.HasNoField(source, "ghost");
        DesignerAssert.HasNoField(source, "commented");
        DesignerAssert.HasField(source, WebControls + "Label", "inHtmlComment");
        Assert.Equal(1, source.Split(" dup;").Length - 1);
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Missing_Inherits_with_CodeBehind_reports_SWWF002_and_inline_pages_are_silent()
    {
        var withCodeBehind = new GeneratorTestHost()
            .WithMarkup("Default.aspx", "<%@ Page Language=\"C#\" CodeBehind=\"Default.aspx.cs\" %><asp:Label ID=\"a\" runat=\"server\" />")
            .Run();
        DesignerAssert.HasDiagnostic(withCodeBehind, "SWWF002");
        Assert.Empty(withCodeBehind.HintNames);

        var inline = new GeneratorTestHost()
            .WithMarkup("Inline.aspx", "<%@ Page Language=\"C#\" %><asp:Label ID=\"a\" runat=\"server\" />")
            .Run();
        DesignerAssert.NoDiagnostics(inline);
        Assert.Empty(inline.HintNames);
    }

    [NetFx48Fact]
    public void Missing_master_page_reports_SWWF004()
    {
        var result = Page("<%@ MasterType VirtualPath=\"~/Missing.Master\" %><asp:Label ID=\"a\" runat=\"server\" />").Run();

        var diagnostic = DesignerAssert.HasDiagnostic(result, "SWWF004");
        Assert.Contains("Missing.Master", diagnostic.GetMessage());
        var source = result.GetSource(DefaultHint);
        Assert.DoesNotContain("Master {", source);
        DesignerAssert.HasField(source, WebControls + "Label", "a");
    }

    [NetFx48Fact]
    public void Unqualified_Inherits_is_resolved_through_RootNamespace()
    {
        var result = new GeneratorTestHost()
            .WithRootNamespace("WebApp")
            .WithMarkup("Default.aspx", "<%@ Page Language=\"C#\" CodeBehind=\"Default.aspx.cs\" Inherits=\"_Default\" %><asp:Label ID=\"a\" runat=\"server\" />")
            .WithSource("Default.aspx.cs", DefaultCodeBehind)
            .Run();

        DesignerAssert.NoDiagnostics(result);
        var source = result.GetSource(DefaultHint);
        Assert.Contains("namespace WebApp {", source);
        DesignerAssert.HasField(source, WebControls + "Label", "a");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Code_behind_class_missing_from_compilation_still_generates_with_SWWF005()
    {
        var result = new GeneratorTestHost()
            .WithMarkup("Default.aspx", "<%@ Page Language=\"C#\" CodeBehind=\"Default.aspx.cs\" Inherits=\"Other.Ns.Missing\" %><asp:Label ID=\"a\" runat=\"server\" />")
            .Run();

        var diagnostic = DesignerAssert.HasDiagnostic(result, "SWWF005");
        Assert.Equal(DiagnosticSeverity.Info, diagnostic.Severity);
        var source = result.GetSource(DefaultHint);
        Assert.Contains("namespace Other.Ns {", source);
        Assert.Contains("partial class Missing {", source);
    }

    [NetFx48Fact]
    public void Code_behind_class_in_a_referenced_assembly_generates_nothing_with_SWWF006()
    {
        var result = new GeneratorTestHost()
            .WithMarkup("Default.aspx", "<%@ Page Language=\"C#\" CodeBehind=\"Default.aspx.cs\" Inherits=\"System.Web.UI.Page\" %><asp:Label ID=\"a\" runat=\"server\" />")
            .Run();

        var diagnostic = DesignerAssert.HasDiagnostic(result, "SWWF006");
        Assert.Equal(DiagnosticSeverity.Info, diagnostic.Severity);
        Assert.Contains("System.Web", diagnostic.GetMessage());
        Assert.Empty(result.HintNames);
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void User_controls_without_code_behind_or_missing_are_typed_as_UserControl()
    {
        var result = new GeneratorTestHost()
            .WithMarkup("Default.aspx",
                PageDirective +
                "<%@ Register TagPrefix=\"uc\" TagName=\"Inline\" Src=\"~/Controls/Inline.ascx\" %>" +
                "<%@ Register TagPrefix=\"uc\" TagName=\"Missing\" Src=\"~/Controls/Missing.ascx\" %>" +
                "<form id=\"form1\" runat=\"server\"><uc:Inline ID=\"inline1\" runat=\"server\" /><uc:Missing ID=\"missing1\" runat=\"server\" /></form>")
            .WithMarkup("Controls/Inline.ascx", "<%@ Control Language=\"C#\" %><asp:Label ID=\"lbl\" runat=\"server\" /><script runat=\"server\">void Page_Load(object s, System.EventArgs e) { }</script>")
            .WithSource("Default.aspx.cs", DefaultCodeBehind)
            .Run();

        var diagnostic = DesignerAssert.HasDiagnostic(result, "SWWF004");
        Assert.Contains("Missing.ascx", diagnostic.GetMessage());
        Assert.Single(result.GeneratorDiagnostics);
        var source = result.GetSource(DefaultHint);
        DesignerAssert.HasField(source, "global::System.Web.UI.UserControl", "inline1");
        DesignerAssert.HasField(source, "global::System.Web.UI.UserControl", "missing1");
        Assert.False(result.HasSource("Controls_Inline.ascx.designer.g.cs"));
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Children_of_a_server_side_head_are_controls_but_the_same_tags_elsewhere_are_generic()
    {
        var result = Page(
            "<html><head runat=\"server\" id=\"head1\">" +
            "<title id=\"pageTitle\">t</title><meta id=\"description\" name=\"description\" content=\"x\" /><link id=\"css\" rel=\"stylesheet\" href=\"a.css\" />" +
            "<script id=\"notAControl\" src=\"x.js\"></script>" +
            "</head><body><form id=\"form1\" runat=\"server\"><meta id=\"bodyMeta\" runat=\"server\" /><div><title id=\"nestedTitle\">x</title></div></form></body></html>").Run();

        DesignerAssert.NoDiagnostics(result);
        var source = result.GetSource(DefaultHint);
        DesignerAssert.HasField(source, HtmlControls + "HtmlHead", "head1");
        DesignerAssert.HasField(source, HtmlControls + "HtmlTitle", "pageTitle");
        DesignerAssert.HasField(source, HtmlControls + "HtmlMeta", "description");
        DesignerAssert.HasField(source, HtmlControls + "HtmlLink", "css");
        DesignerAssert.HasNoField(source, "notAControl");
        DesignerAssert.HasField(source, HtmlControls + "HtmlGenericControl", "bodyMeta");
        DesignerAssert.HasNoField(source, "nestedTitle");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Web_config_registrations_are_scoped_to_their_folder_and_location()
    {
        var result = new GeneratorTestHost()
            .WithWebConfig(
                "<configuration>" +
                "<system.web><pages><controls><add tagPrefix=\"ex\" namespace=\"WebApp.Controls\" /></controls></pages></system.web>" +
                "<location path=\"Admin\"><system.web><pages><controls><add tagPrefix=\"adm\" namespace=\"WebApp.Admin\" /></controls></pages></system.web></location>" +
                "</configuration>")
            .WithMarkup("Admin/Reports/Web.config",
                "<configuration><system.web><pages><controls><add tagPrefix=\"rep\" namespace=\"WebApp.Reports\" /></controls></pages></system.web></configuration>")
            .WithMarkup("Default.aspx", PageDirective + "<form id=\"form1\" runat=\"server\"><ex:GreetingLabel ID=\"a\" runat=\"server\" /><adm:AdminLabel ID=\"b\" runat=\"server\" /></form>")
            .WithMarkup("Admin/Reports/Sales.aspx",
                "<%@ Page Language=\"C#\" CodeBehind=\"Sales.aspx.cs\" Inherits=\"WebApp.Sales\" %>" +
                "<form id=\"form1\" runat=\"server\"><ex:GreetingLabel ID=\"a\" runat=\"server\" /><adm:AdminLabel ID=\"b\" runat=\"server\" /><rep:ReportLabel ID=\"c\" runat=\"server\" /></form>")
            .WithSource("Code.cs",
                "namespace WebApp { public partial class _Default : System.Web.UI.Page { } public partial class Sales : System.Web.UI.Page { } }" +
                "namespace WebApp.Controls { public class GreetingLabel : System.Web.UI.WebControls.Label { } }" +
                "namespace WebApp.Admin { public class AdminLabel : System.Web.UI.WebControls.Label { } }" +
                "namespace WebApp.Reports { public class ReportLabel : System.Web.UI.WebControls.Label { } }")
            .Run();

        // The root page cannot see the Admin-scoped prefix.
        var diagnostic = DesignerAssert.HasDiagnostic(result, "SWWF001");
        Assert.Contains("adm:AdminLabel", diagnostic.GetMessage());
        Assert.Single(result.GeneratorDiagnostics);
        var root = result.GetSource(DefaultHint);
        DesignerAssert.HasField(root, "global::WebApp.Controls.GreetingLabel", "a");
        DesignerAssert.HasNoField(root, "b");

        var sales = result.GetSource("Admin_Reports_Sales.aspx.designer.g.cs");
        DesignerAssert.HasField(sales, "global::WebApp.Controls.GreetingLabel", "a");
        DesignerAssert.HasField(sales, "global::WebApp.Admin.AdminLabel", "b");
        DesignerAssert.HasField(sales, "global::WebApp.Reports.ReportLabel", "c");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Template_instance_attribute_is_inherited_by_overriding_properties()
    {
        var result = Page(
            "<%@ Register TagPrefix=\"my\" Namespace=\"WebApp.Controls\" %>" +
            "<form id=\"form1\" runat=\"server\">" +
            "<my:DerivedPanel ID=\"pnl\" runat=\"server\"><Body><asp:Label ID=\"inSingle\" runat=\"server\" /></Body>" +
            "<Rows><asp:Label ID=\"inMultiple\" runat=\"server\" /></Rows></my:DerivedPanel>" +
            "</form>",
            DefaultCodeBehind +
            "namespace WebApp.Controls { " +
            "public class BasePanel : System.Web.UI.WebControls.WebControl { " +
            "  [System.Web.UI.TemplateInstance(System.Web.UI.TemplateInstance.Single)] public virtual System.Web.UI.ITemplate Body { get; set; } " +
            "  public virtual System.Web.UI.ITemplate Rows { get; set; } } " +
            "public class DerivedPanel : BasePanel { " +
            "  public override System.Web.UI.ITemplate Body { get; set; } " +
            "  public override System.Web.UI.ITemplate Rows { get; set; } } }").Run();

        DesignerAssert.NoDiagnostics(result);
        var source = result.GetSource(DefaultHint);
        DesignerAssert.HasField(source, "global::WebApp.Controls.DerivedPanel", "pnl");
        DesignerAssert.HasField(source, WebControls + "Label", "inSingle");
        DesignerAssert.HasNoField(source, "inMultiple");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Ids_that_are_keywords_are_escaped()
    {
        var result = Page("<form id=\"form1\" runat=\"server\"><asp:Label ID=\"class\" runat=\"server\" /><asp:Label ID=\"value\" runat=\"server\" /></form>").Run();

        DesignerAssert.NoDiagnostics(result);
        var source = result.GetSource(DefaultHint);
        Assert.Contains("protected global::System.Web.UI.WebControls.Label @class;", source);
        Assert.Contains("/// class control.", source);
        DesignerAssert.HasField(source, WebControls + "Label", "value");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Nested_code_behind_classes_get_nested_partial_declarations()
    {
        var result = new GeneratorTestHost()
            .WithMarkup("Default.aspx", "<%@ Page Language=\"C#\" CodeBehind=\"Default.aspx.cs\" Inherits=\"WebApp.Pages.Outer.Inner\" %><form id=\"form1\" runat=\"server\"><asp:Label ID=\"lbl\" runat=\"server\" /></form>")
            .WithSource("Default.aspx.cs", "namespace WebApp.Pages { public partial class Outer { public partial class Inner : System.Web.UI.Page { } } }")
            .Run();

        DesignerAssert.NoDiagnostics(result);
        var source = result.GetSource(DefaultHint);
        Assert.Contains("namespace WebApp.Pages {", source);
        Assert.Contains("    partial class Outer {", source);
        Assert.Contains("        partial class Inner {", source);
        DesignerAssert.HasField(source, WebControls + "Label", "lbl");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Without_System_Web_nothing_is_generated_and_nothing_is_reported()
    {
        var result = Page("<asp:Label ID=\"a\" runat=\"server\" />", "namespace WebApp { public partial class _Default { } }").Run(referenceSystemWeb: false);

        DesignerAssert.NoDiagnostics(result);
        Assert.Empty(result.HintNames);
    }
}
