using Microsoft.CodeAnalysis;
using MSBuild.SDK.SystemWeb.WebForms.Generator.Emit;
using MSBuild.SDK.SystemWeb.WebForms.Tests.Infrastructure;

namespace MSBuild.SDK.SystemWeb.WebForms.Tests;

public class VisualBasicGeneratorTests
{
    private const string PageDirective = "<%@ Page Language=\"VB\" AutoEventWireup=\"false\" CodeBehind=\"Default.aspx.vb\" Inherits=\"WebApp._Default\" %>\r\n";
    private const string DefaultHint = "Default.aspx.designer.g.vb";
    private const string WebControls = "Global.System.Web.UI.WebControls.";
    private const string HtmlControls = "Global.System.Web.UI.HtmlControls.";

    private static GeneratorTestHost VbPage(string body, string codeBehind)
        => new GeneratorTestHost().WithLanguage(LanguageNames.VisualBasic).WithMarkup("Default.aspx", PageDirective + body).WithSource("Default.aspx.vb", codeBehind);

    [NetFx48Fact]
    public void Basic_vb_page_generates_WithEvents_fields_usable_from_Handles_clauses()
    {
        var result = VbPage(
            "<form id=\"form1\" runat=\"server\"><asp:Label ID=\"lblName\" runat=\"server\" /><asp:Button ID=\"btn\" runat=\"server\" /></form>",
            "Public Class _Default\r\n" +
            "    Inherits System.Web.UI.Page\r\n" +
            "    Protected Sub btn_Click(sender As Object, e As EventArgs) Handles btn.Click\r\n" +
            "        lblName.Text = \"clicked\"\r\n" +
            "    End Sub\r\n" +
            "End Class\r\n").Run();

        DesignerAssert.NoDiagnostics(result);
        var source = result.GetSource(DefaultHint);
        Assert.Contains("' <auto-generated>", source);
        Assert.Contains("Option Strict On", source);
        Assert.Contains("Option Explicit On", source);
        Assert.DoesNotContain("Namespace ", source);
        Assert.Contains("Partial Class _Default", source);
        DesignerAssert.HasVbField(source, HtmlControls + "HtmlForm", "form1");
        DesignerAssert.HasVbField(source, WebControls + "Label", "lblName");
        DesignerAssert.HasVbField(source, WebControls + "Button", "btn");
        Assert.Contains("'''To modify move field declaration from designer file to code-behind file.", source);
        Assert.Contains("End Class", source);
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Namespaces_are_relative_to_the_root_namespace()
    {
        var result = new GeneratorTestHost()
            .WithLanguage(LanguageNames.VisualBasic)
            .WithMarkup("Admin/Page1.aspx", "<%@ Page Language=\"VB\" CodeBehind=\"Page1.aspx.vb\" Inherits=\"WebApp.Admin.Page1\" %><asp:Label ID=\"a\" runat=\"server\" />")
            .WithMarkup("Other.aspx", "<%@ Page Language=\"VB\" CodeBehind=\"Other.aspx.vb\" Inherits=\"Elsewhere.Other\" %><asp:Label ID=\"b\" runat=\"server\" />")
            .WithSource("Pages.vb",
                "Namespace Admin\r\n    Public Class Page1\r\n        Inherits System.Web.UI.Page\r\n    End Class\r\nEnd Namespace\r\n" +
                "Namespace Global.Elsewhere\r\n    Public Class Other\r\n        Inherits System.Web.UI.Page\r\n    End Class\r\nEnd Namespace\r\n")
            .Run();

        DesignerAssert.NoDiagnostics(result);
        var admin = result.GetSource("Admin_Page1.aspx.designer.g.vb");
        Assert.Contains("Namespace Admin\r\n", admin);
        Assert.Contains("End Namespace", admin);
        DesignerAssert.HasVbField(admin, WebControls + "Label", "a");

        var other = result.GetSource("Other.aspx.designer.g.vb");
        Assert.Contains("Namespace Global.Elsewhere\r\n", other);
        DesignerAssert.HasVbField(other, WebControls + "Label", "b");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Member_and_id_comparisons_are_case_insensitive_in_vb()
    {
        var result = VbPage(
            "<form id=\"form1\" runat=\"server\"><asp:Label ID=\"lblName\" runat=\"server\" /><asp:Label ID=\"Dup\" runat=\"server\" /><asp:Label ID=\"DUP\" runat=\"server\" /></form>",
            "Public Class _Default\r\n    Inherits System.Web.UI.Page\r\n    Protected WithEvents LBLNAME As Global.System.Web.UI.WebControls.Label\r\nEnd Class\r\n").Run();

        DesignerAssert.NoDiagnostics(result);
        var source = result.GetSource(DefaultHint);
        DesignerAssert.HasNoVbField(source, "lblName");
        Assert.Equal(1, source.Split("WithEvents Dup As").Length - 1 + source.Split("WithEvents DUP As").Length - 1);
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void MasterType_produces_a_Shadows_property_and_user_controls_are_typed()
    {
        var result = new GeneratorTestHost()
            .WithLanguage(LanguageNames.VisualBasic)
            .WithMarkup("Site.Master", "<%@ Master Language=\"VB\" CodeBehind=\"Site.Master.vb\" Inherits=\"WebApp.SiteMaster\" %><form id=\"form1\" runat=\"server\"><asp:ContentPlaceHolder ID=\"Main\" runat=\"server\" /></form>")
            .WithMarkup("Controls/Hello.ascx", "<%@ Control Language=\"VB\" CodeBehind=\"Hello.ascx.vb\" Inherits=\"WebApp.Controls.Hello\" %><asp:Label ID=\"lblHello\" runat=\"server\" />")
            .WithMarkup("Default.aspx",
                "<%@ Page Language=\"VB\" MasterPageFile=\"~/Site.Master\" CodeBehind=\"Default.aspx.vb\" Inherits=\"WebApp._Default\" %>" +
                "<%@ MasterType VirtualPath=\"~/Site.Master\" %><%@ Register TagPrefix=\"uc\" TagName=\"Hello\" Src=\"~/Controls/Hello.ascx\" %>" +
                "<asp:Content ContentPlaceHolderID=\"Main\" runat=\"server\"><uc:Hello ID=\"hello1\" runat=\"server\" /></asp:Content>")
            .WithSource("Code.vb",
                "Public Class SiteMaster\r\n    Inherits System.Web.UI.MasterPage\r\n    Public Property Heading As String\r\nEnd Class\r\n" +
                "Public Class _Default\r\n    Inherits System.Web.UI.Page\r\n    Protected Sub Page_Load(sender As Object, e As EventArgs) Handles Me.Load\r\n        Master.Heading = hello1.ID\r\n    End Sub\r\nEnd Class\r\n" +
                "Namespace Controls\r\n    Public Class Hello\r\n        Inherits System.Web.UI.UserControl\r\n    End Class\r\nEnd Namespace\r\n")
            .Run();

        DesignerAssert.NoDiagnostics(result);
        var page = result.GetSource(DefaultHint);
        Assert.Contains("Public Shadows ReadOnly Property Master() As Global.WebApp.SiteMaster", page);
        Assert.Contains("Return CType(MyBase.Master, Global.WebApp.SiteMaster)", page);
        DesignerAssert.HasVbField(page, "Global.WebApp.Controls.Hello", "hello1");
        var control = result.GetSource("Controls_Hello.ascx.designer.g.vb");
        Assert.Contains("Namespace Controls\r\n", control);
        DesignerAssert.HasVbField(control, WebControls + "Label", "lblHello");
        DesignerAssert.HasVbField(result.GetSource("Site.Master.designer.g.vb"), WebControls + "ContentPlaceHolder", "Main");
        DesignerAssert.Compiles(result);
    }

    [NetFx48Fact]
    public void Keyword_ids_are_bracket_escaped_and_nested_classes_nest()
    {
        var result = new GeneratorTestHost()
            .WithLanguage(LanguageNames.VisualBasic)
            // "Error" would be skipped (Page already has an Error event, as in VS); Date and Loop are keywords with no such clash.
            .WithMarkup("Default.aspx", "<%@ Page Language=\"VB\" CodeBehind=\"Default.aspx.vb\" Inherits=\"WebApp.Outer.Inner\" %><asp:Label ID=\"Date\" runat=\"server\" /><asp:Label ID=\"Loop\" runat=\"server\" /><asp:Label ID=\"Error\" runat=\"server\" />")
            .WithSource("Default.aspx.vb", "Public Class Outer\r\n    Public Class Inner\r\n        Inherits System.Web.UI.Page\r\n    End Class\r\nEnd Class\r\n")
            .Run();

        DesignerAssert.NoDiagnostics(result);
        var source = result.GetSource(DefaultHint);
        Assert.Contains("Partial Class Outer\r\n", source);
        Assert.Contains("    Partial Class Inner\r\n", source);
        Assert.Contains("Protected WithEvents [Date] As " + WebControls + "Label", source);
        Assert.Contains("Protected WithEvents [Loop] As " + WebControls + "Label", source);
        DesignerAssert.HasNoVbField(source, "Error");
        DesignerAssert.Compiles(result);
    }
}

public class IdentifierRulesTests
{
    [Theory]
    [InlineData("lblName", true)]
    [InlineData("_x1", true)]
    [InlineData("class", true)]
    [InlineData("1abc", false)]
    [InlineData("a-b", false)]
    [InlineData("a b", false)]
    [InlineData("", false)]
    [InlineData("_", false)]
    [InlineData("æøå", true)]
    public void Validates_identifiers(string name, bool valid)
    {
        Assert.Equal(valid, IdentifierRules.IsValidIdentifier(name));
    }

    [Theory]
    [InlineData("class", LanguageNames.CSharp, "@class")]
    [InlineData("value", LanguageNames.CSharp, "value")]
    [InlineData("Error", LanguageNames.VisualBasic, "[Error]")]
    [InlineData("DATE", LanguageNames.VisualBasic, "[DATE]")]
    [InlineData("class", LanguageNames.VisualBasic, "[class]")]
    [InlineData("Text", LanguageNames.VisualBasic, "Text")]
    public void Escapes_keywords_per_language(string name, string language, string expected)
    {
        Assert.Equal(expected, IdentifierRules.Escape(name, language));
    }

    [Theory]
    [InlineData("WebApp", "WebApp", null)]
    [InlineData("webapp", "WebApp", null)]
    [InlineData("WebApp.Admin.Pages", "WebApp", "Admin.Pages")]
    [InlineData("Other.Ns", "WebApp", "Global.Other.Ns")]
    [InlineData("WebAppX", "WebApp", "Global.WebAppX")]
    [InlineData("Any.Ns", null, "Any.Ns")]
    [InlineData(null, "WebApp", null)]
    public void Vb_namespaces_are_relative_to_the_root_namespace(string? full, string? root, string? expected)
    {
        Assert.Equal(expected, VisualBasicDesignerEmitter.RelativeNamespace(full, root));
    }
}
