using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using MSBuild.SDK.SystemWeb.WebForms.Generator.Model;

namespace MSBuild.SDK.SystemWeb.WebForms.Generator.Emit
{
    /// <summary>Writes a designer file in the same shape Visual Studio produces for Web Application Projects.</summary>
    public static class CSharpDesignerEmitter
    {
        private const string NewLine = "\r\n";

        public static string Emit(DesignerModel model, string sourceRelativePath)
        {
            var sb = new StringBuilder();
            sb.Append("//------------------------------------------------------------------------------").Append(NewLine);
            sb.Append("// <auto-generated>").Append(NewLine);
            sb.Append("//     This code was generated by a tool.").Append(NewLine);
            sb.Append("//     Generated by MSBuild.SDK.SystemWeb.WebForms from ").Append(sourceRelativePath).Append(NewLine);
            sb.Append("//").Append(NewLine);
            sb.Append("//     Changes to this file may cause incorrect behavior and will be lost if").Append(NewLine);
            sb.Append("//     the code is regenerated.").Append(NewLine);
            sb.Append("// </auto-generated>").Append(NewLine);
            sb.Append("//------------------------------------------------------------------------------").Append(NewLine);
            sb.Append(NewLine);

            var indent = string.Empty;
            if (!string.IsNullOrEmpty(model.Namespace))
            {
                sb.Append("namespace ").Append(model.Namespace).Append(" {").Append(NewLine);
                sb.Append("    ").Append(NewLine);
                sb.Append("    ").Append(NewLine);
                indent = "    ";
            }

            foreach (var containingType in model.ContainingTypes)
            {
                sb.Append(indent).Append("partial class ").Append(Escape(containingType)).Append(" {").Append(NewLine);
                indent += "    ";
            }

            sb.Append(indent).Append("partial class ").Append(Escape(model.ClassName)).Append(" {").Append(NewLine);

            var memberIndent = indent + "    ";
            foreach (var field in model.Fields)
            {
                sb.Append(memberIndent).Append(NewLine);
                sb.Append(memberIndent).Append("/// <summary>").Append(NewLine);
                sb.Append(memberIndent).Append("/// ").Append(field.Name).Append(" control.").Append(NewLine);
                sb.Append(memberIndent).Append("/// </summary>").Append(NewLine);
                sb.Append(memberIndent).Append("/// <remarks>").Append(NewLine);
                sb.Append(memberIndent).Append("/// Auto-generated field.").Append(NewLine);
                sb.Append(memberIndent).Append("/// To modify move field declaration from designer file to code-behind file.").Append(NewLine);
                sb.Append(memberIndent).Append("/// </remarks>").Append(NewLine);
                sb.Append(memberIndent).Append("protected ").Append(field.FullyQualifiedType).Append(' ').Append(Escape(field.Name)).Append(';').Append(NewLine);
            }

            AppendTypedProperty(sb, memberIndent, model.Master);
            AppendTypedProperty(sb, memberIndent, model.PreviousPage);

            sb.Append(indent).Append('}').Append(NewLine);
            for (var i = 0; i < model.ContainingTypes.Count; i++)
            {
                indent = indent.Substring(4);
                sb.Append(indent).Append('}').Append(NewLine);
            }

            if (!string.IsNullOrEmpty(model.Namespace))
            {
                sb.Append('}').Append(NewLine);
            }

            return sb.ToString();
        }

        /// <summary>Prefixes reserved keywords with <c>@</c> so an <c>ID="class"</c> still yields a legal field.</summary>
        private static string Escape(string identifier)
        {
            return SyntaxFacts.GetKeywordKind(identifier) != SyntaxKind.None ? "@" + identifier : identifier;
        }

        private static void AppendTypedProperty(StringBuilder sb, string indent, TypedProperty? property)
        {
            if (property is null)
            {
                return;
            }

            sb.Append(indent).Append(NewLine);
            sb.Append(indent).Append("/// <summary>").Append(NewLine);
            sb.Append(indent).Append("/// ").Append(property.Name).Append(" property.").Append(NewLine);
            sb.Append(indent).Append("/// </summary>").Append(NewLine);
            sb.Append(indent).Append("/// <remarks>").Append(NewLine);
            sb.Append(indent).Append("/// Auto-generated property.").Append(NewLine);
            sb.Append(indent).Append("/// </remarks>").Append(NewLine);
            sb.Append(indent).Append("public new ").Append(property.FullyQualifiedType).Append(' ').Append(property.Name).Append(" {").Append(NewLine);
            sb.Append(indent).Append("    get {").Append(NewLine);
            sb.Append(indent).Append("        return ((").Append(property.FullyQualifiedType).Append(")(base.").Append(property.Name).Append("));").Append(NewLine);
            sb.Append(indent).Append("    }").Append(NewLine);
            sb.Append(indent).Append('}').Append(NewLine);
        }
    }
}
