using System;
using System.Text;
using Microsoft.CodeAnalysis;
using MSBuild.SDK.SystemWeb.WebForms.Generator.Model;

namespace MSBuild.SDK.SystemWeb.WebForms.Generator.Emit
{
    /// <summary>
    /// Writes a designer file in the same shape Visual Studio produces for VB Web Application Projects:
    /// <c>Protected WithEvents</c> fields (so <c>Handles</c> clauses work) and a <c>Namespace</c> block relative to the
    /// project's root namespace, which VB applies implicitly to every declaration.
    /// </summary>
    public static class VisualBasicDesignerEmitter
    {
        private const string NewLine = "\r\n";

        public static string Emit(DesignerModel model, string sourceRelativePath, string? rootNamespace)
        {
            var sb = new StringBuilder();
            sb.Append("'------------------------------------------------------------------------------").Append(NewLine);
            sb.Append("' <auto-generated>").Append(NewLine);
            sb.Append("'     This code was generated by a tool.").Append(NewLine);
            sb.Append("'     Generated by MSBuild.SDK.SystemWeb.WebForms from ").Append(sourceRelativePath).Append(NewLine);
            sb.Append("'").Append(NewLine);
            sb.Append("'     Changes to this file may cause incorrect behavior and will be lost if").Append(NewLine);
            sb.Append("'     the code is regenerated.").Append(NewLine);
            sb.Append("' </auto-generated>").Append(NewLine);
            sb.Append("'------------------------------------------------------------------------------").Append(NewLine);
            sb.Append(NewLine);
            sb.Append("Option Strict On").Append(NewLine);
            sb.Append("Option Explicit On").Append(NewLine);
            sb.Append(NewLine);

            var indent = string.Empty;
            var ns = RelativeNamespace(model.Namespace, rootNamespace);
            if (ns is not null)
            {
                sb.Append("Namespace ").Append(ns).Append(NewLine);
                sb.Append("    ").Append(NewLine);
                indent = "    ";
            }

            foreach (var containingType in model.ContainingTypes)
            {
                sb.Append(indent).Append("Partial Class ").Append(Escape(containingType)).Append(NewLine);
                indent += "    ";
            }

            sb.Append(indent).Append("Partial Class ").Append(Escape(model.ClassName)).Append(NewLine);

            var memberIndent = indent + "    ";
            foreach (var field in model.Fields)
            {
                sb.Append(memberIndent).Append(NewLine);
                sb.Append(memberIndent).Append("'''<summary>").Append(NewLine);
                sb.Append(memberIndent).Append("'''").Append(field.Name).Append(" control.").Append(NewLine);
                sb.Append(memberIndent).Append("'''</summary>").Append(NewLine);
                sb.Append(memberIndent).Append("'''<remarks>").Append(NewLine);
                sb.Append(memberIndent).Append("'''Auto-generated field.").Append(NewLine);
                sb.Append(memberIndent).Append("'''To modify move field declaration from designer file to code-behind file.").Append(NewLine);
                sb.Append(memberIndent).Append("'''</remarks>").Append(NewLine);
                sb.Append(memberIndent).Append("Protected WithEvents ").Append(Escape(field.Name)).Append(" As ").Append(field.FullyQualifiedType).Append(NewLine);
            }

            AppendTypedProperty(sb, memberIndent, model.Master);
            AppendTypedProperty(sb, memberIndent, model.PreviousPage);

            sb.Append(indent).Append("End Class").Append(NewLine);
            for (var i = 0; i < model.ContainingTypes.Count; i++)
            {
                indent = indent.Substring(4);
                sb.Append(indent).Append("End Class").Append(NewLine);
            }

            if (ns is not null)
            {
                sb.Append("End Namespace").Append(NewLine);
            }

            return sb.ToString();
        }

        /// <summary>
        /// The <c>Namespace</c> to declare, given that VB nests every declaration inside the project's root namespace:
        /// none when the class lives directly in the root namespace, the remainder when it lives below it,
        /// and <c>Global.</c>-qualified when it lives outside it.
        /// </summary>
        public static string? RelativeNamespace(string? fullNamespace, string? rootNamespace)
        {
            if (string.IsNullOrEmpty(fullNamespace))
            {
                return null;
            }

            if (string.IsNullOrEmpty(rootNamespace))
            {
                return fullNamespace;
            }

            if (string.Equals(fullNamespace, rootNamespace, StringComparison.OrdinalIgnoreCase))
            {
                return null;
            }

            if (fullNamespace!.StartsWith(rootNamespace + ".", StringComparison.OrdinalIgnoreCase))
            {
                return fullNamespace.Substring(rootNamespace!.Length + 1);
            }

            return "Global." + fullNamespace;
        }

        private static string Escape(string identifier) => IdentifierRules.Escape(identifier, LanguageNames.VisualBasic);

        private static void AppendTypedProperty(StringBuilder sb, string indent, TypedProperty? property)
        {
            if (property is null)
            {
                return;
            }

            sb.Append(indent).Append(NewLine);
            sb.Append(indent).Append("'''<summary>").Append(NewLine);
            sb.Append(indent).Append("'''").Append(property.Name).Append(" property.").Append(NewLine);
            sb.Append(indent).Append("'''</summary>").Append(NewLine);
            sb.Append(indent).Append("'''<remarks>").Append(NewLine);
            sb.Append(indent).Append("'''Auto-generated property.").Append(NewLine);
            sb.Append(indent).Append("'''</remarks>").Append(NewLine);
            sb.Append(indent).Append("Public Shadows ReadOnly Property ").Append(property.Name).Append("() As ").Append(property.FullyQualifiedType).Append(NewLine);
            sb.Append(indent).Append("    Get").Append(NewLine);
            sb.Append(indent).Append("        Return CType(MyBase.").Append(property.Name).Append(", ").Append(property.FullyQualifiedType).Append(')').Append(NewLine);
            sb.Append(indent).Append("    End Get").Append(NewLine);
            sb.Append(indent).Append("End Property").Append(NewLine);
        }
    }
}
